catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade
catalog:
  '@antfu/eslint-config': ^6.7.3
  '@iconify/json': ^2.2.443
  '@shikijs/markdown-it': ^3.23.0
  '@shikijs/transformers': ^3.23.0
  '@types/fs-extra': ^11.0.4
  '@types/lodash-es': ^4.17.12
  '@types/markdown-it': ^14.1.2
  '@types/node': ^24.10.14
  '@unhead/vue': ^2.1.8
  '@unocss/preset-wind3': ^66.6.1
  '@vercel/analytics': ^1.6.1
  '@vercel/speed-insights': ^1.3.1
  '@vitejs/plugin-vue': ^6.0.4
  '@vueuse/core': ^14.2.1
  '@vueuse/head': ^2.0.0
  dayjs: ^1.11.19
  diacritics: ^1.3.0
  eslint: ^9.39.3
  esno: ^4.8.0
  execa: ^9.6.1
  fast-glob: ^3.3.3
  feed: ^5.2.0
  fs-extra: ^11.3.3
  gray-matter: ^4.0.3
  husky: ^9.1.7
  image-size: ^2.0.2
  lint-staged: ^16.2.7
  lodash-es: ^4.17.23
  markdown-it: ^14.1.1
  markdown-it-anchor: ^9.2.0
  markdown-it-link-attributes: ^4.0.1
  markdown-it-table-of-contents: ^1.1.0
  typescript: ^5.9.3
  unocss: ^66.6.1
  unplugin-icons: ^22.5.0
  unplugin-vue-components: ^31.0.0
  unplugin-vue-markdown: ^29.2.0
  vite: ^7.3.1
  vite-plugin-inspect: ^11.3.3
  vite-plugin-pages: ^0.33.3
  vite-ssg: ^28.3.0
  vue: ^3.5.29
  vue-router: ^5.0.3
  vue-tsc: ^3.2.5
onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
