catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade

catalog:
  '@antfu/eslint-config': ^6.4.2
  '@iconify/json': ^2.2.323
  '@shikijs/markdown-it': ^3.2.1
  '@shikijs/transformers': ^3.2.1
  '@types/fs-extra': ^11.0.4
  '@types/lodash-es': ^4.17.12
  '@types/markdown-it': ^14.1.2
  '@types/node': ^22.14.0
  '@unhead/vue': ^2.0.3
  '@unocss/preset-wind3': ^66.5.1
  '@vercel/speed-insights': ^1.2.0
  '@vitejs/plugin-vue': ^6.0.0
  '@vueuse/core': ^14.1.0
  '@vueuse/head': ^2.0.0
  dayjs: ^1.11.13
  diacritics: ^1.3.0
  eslint: ^9.23.0
  esno: ^4.8.0
  execa: ^9.5.2
  fast-glob: ^3.3.3
  feed: ^5.0.0
  fs-extra: ^11.3.0
  gray-matter: ^4.0.3
  husky: ^9.1.7
  lint-staged: ^16.0.0
  lodash-es: ^4.17.21
  markdown-it: ^14.1.0
  markdown-it-anchor: ^9.2.0
  markdown-it-link-attributes: ^4.0.1
  markdown-it-table-of-contents: ^1.0.0
  typescript: ^5.8.2
  unocss: ^66.5.1
  unplugin-icons: ^22.1.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-markdown: ^29.1.0
  vite: ^7.2.6
  vite-plugin-inspect: ^11.0.0
  vite-plugin-pages: ^0.33.0
  vite-ssg: ^28.0.0
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^3.0.6

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
